CREATE TABLE ADMINISTRATOR (
    ADMIN_ID NUMBER(19, 0) NOT NULL,
    ACCOUNT_SERIAL VARCHAR2(2000),
    EMAIL VARCHAR2(2000),
    PASSWORD VARCHAR2(50) NOT NULL,
    CONSTRAINT ADMIN_PK PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE BATTERY (
    BATTERY_ID NUMBER(19, 0) NOT NULL,
    AVAILABLE_STATUS NUMBER,
    CURRENT_CAPACITY NUMBER(38, 2) NOT NULL,
    CURR_CHARGE_TIMES NUMBER NOT NULL,
    MANUFACTURING_DATE TIMESTAMP(7) NOT NULL,
    STATION_ID NUMBER(19, 0),
    BATTERY_TYPE_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT BATTERY_PK PRIMARY KEY (BATTERY_ID),
    CONSTRAINT BATTERY_FK1 FOREIGN KEY (BATTERY_TYPE_ID) REFERENCES BATTERY_TYPE(BATTERY_TYPE_ID)
);

CREATE TABLE BATTERY_TYPE (
    BATTERY_TYPE_ID NUMBER(19, 0) NOT NULL,
    MAX_CHARGE_TIMES NUMBER NOT NULL,
    TOTAL_CAPACITY VARCHAR2(2000),
    NAME VARCHAR2(2000),
    CONSTRAINT BATTERY_TYPE_PK PRIMARY KEY (BATTERY_TYPE_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(19, 0) NOT NULL,
    ACCOUNT_SERIAL VARCHAR2(2000),
    EMAIL VARCHAR2(2000),
    USERNAME VARCHAR2(30),
    PASSWORD VARCHAR2(50) DEFAULT 'N''123456''' NOT NULL,
    PROFILE_PHOTO BLOB,
    CREATE_TIME TIMESTAMP(7) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    IDENTITYNUMBER VARCHAR2(50),
    NAME VARCHAR2(30),
    GENDER VARCHAR2(3),
    POSITIONS NUMBER NOT NULL,
    SALARY NUMBER NOT NULL,
    STATION_ID NUMBER(19, 0),
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE EMPLOYEE_MAINTENANCEITEM (
    EMPLOYEE_ID NUMBER(19, 0) NOT NULL,
    MAINTENANCE_ID NUMBER(19, 0) NOT NULL
);

CREATE TABLE KPI (
    KPI_ID NUMBER(19, 0) NOT NULL,
    TOTAL_PERFORMANCE NUMBER(38, 2) NOT NULL,
    SERVICE_FREQUENCY NUMBER NOT NULL,
    SCORE NUMBER(38, 2) NOT NULL,
    EMPLOYEE_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT KPI_PK PRIMARY KEY (KPI_ID),
    CONSTRAINT KPI_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE MAINTENANCE_ITEM (
    MAINTENANCE_ITEM_ID NUMBER(19, 0) NOT NULL,
    MAINTENANCE_LOCATION VARCHAR2(50) NOT NULL,
    NOTE VARCHAR2(2000),
    TITLE VARCHAR2(2000),
    LONGITUDE NUMBER(38, 2) NOT NULL,
    LATITUDE NUMBER(38, 2) NOT NULL,
    SERVICE_TIME TIMESTAMP(7),
    ORDER_SUBMISSION_TIME TIMESTAMP(6) NOT NULL,
    APPOINT_TIME TIMESTAMP(7) NOT NULL,
    ORDER_STATUS NUMBER NOT NULL,
    SCORE NUMBER(38, 2) NOT NULL,
    EVALUATION VARCHAR2(2000),
    VEHICLE_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT MAINTENANCE_ITEM_PK PRIMARY KEY (MAINTENANCE_ITEM_ID)
);

CREATE TABLE NEWS (
    ANNOUNCEMENT_ID NUMBER(19, 0) NOT NULL,
    PUBLISH_TIME TIMESTAMP(7) NOT NULL,
    PUBLISH_POS NUMBER NOT NULL,
    TITLE VARCHAR2(50),
    CONTENTS CLOB,
    LIKES NUMBER NOT NULL,
    VIEW_COUNT NUMBER NOT NULL,
    ADMIN_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT NEWS_PK PRIMARY KEY (ANNOUNCEMENT_ID),
    CONSTRAINT NEWS_FK1 FOREIGN KEY (ADMIN_ID) REFERENCES ADMINISTRATOR(ADMIN_ID)
);

CREATE TABLE OWNERPOS (
    OWNER_ID NUMBER(19, 0) NOT NULL,
    ADDRESS VARCHAR2(2000) NOT NULL,
    CONSTRAINT OWNERPOS_PK PRIMARY KEY (OWNER_ID)
);

CREATE TABLE SWITCH_LOG (
    SWITCH_SERVICE_ID NUMBER(19, 0) NOT NULL,
    SWITCH_TIME TIMESTAMP(7) NOT NULL,
    SCORE NUMBER(38, 2) NOT NULL,
    EVALUATION VARCHAR2(2000),
    SERVICE_FEE REAL NOT NULL,
    BATTERY_ON_ID NUMBER(19, 0) NOT NULL,
    BATTERY_OFF_IF NUMBER(19, 0) NOT NULL,
    SWITCH_REQUEST_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT SWITCH_LOG_PK PRIMARY KEY (SWITCH_SERVICE_ID),
    CONSTRAINT SWITCH_LOG_FK1 FOREIGN KEY (BATTERY_ON_ID) REFERENCES BATTERY(BATTERY_ID),
    CONSTRAINT SWITCH_LOG_FK2 FOREIGN KEY (BATTERY_OFF_IF) REFERENCES BATTERY(BATTERY_ID),
    CONSTRAINT SWITCH_LOG_FK3 FOREIGN KEY (SWITCH_REQUEST_ID) REFERENCES SWITCH_REQUEST(SWITCH_REQUEST_ID)
);

CREATE TABLE SWITCH_REQUEST (
    SWITCH_REQUEST_ID NUMBER(19, 0) NOT NULL,
    SWITCH_TYPE NUMBER NOT NULL,
    REQUEST_TIME TIMESTAMP(7) NOT NULL,
    POSITION VARCHAR2(50),
    LONGITUDE NUMBER(38, 2) NOT NULL,
    LATITUDE NUMBER(38, 2) NOT NULL,
    NOTES VARCHAR2(255),
    DATE TIMESTAMP(7) NOT NULL,
    REQUEST_STATUS NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER(19, 0) NOT NULL,
    VEHICLE_ID NUMBER(19, 0) NOT NULL,
    BATTERY_TYPE_ID NUMBER(19, 0) NOT NULL,
    PERIOD NUMBER,
    CONSTRAINT SWITCH_REQUEST_PK PRIMARY KEY (SWITCH_REQUEST_ID),
    CONSTRAINT SWITCH_REQUEST_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT SWITCH_REQUEST_FK2 FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID),
    CONSTRAINT SWITCH_REQUEST_FK3 FOREIGN KEY (BATTERY_TYPE_ID) REFERENCES BATTERY_TYPE(BATTERY_TYPE_ID)
);

CREATE TABLE SWITCH_STATION (
    STATION_ID NUMBER(19, 0) NOT NULL,
    STATION_NAME VARCHAR2(50),
    SERVICE_FEE REAL NOT NULL,
    ELECTRICITY_FEE REAL NOT NULL,
    PARKING_FEE VARCHAR2(2000) NOT NULL,
    QUEUE_LENGTH NUMBER NOT NULL,
    LONGITUDE NUMBER(38, 2) NOT NULL,
    LATITUDE NUMBER(38, 2) NOT NULL,
    FAILURE_STATUS NUMBER NOT NULL,
    BATTERY_CAPACITY NUMBER NOT NULL,
    AVAILABLE_BATTERY_COUNT NUMBER NOT NULL,
    CITY VARCHAR2(2000),
    TAGS VARCHAR2(2000),
    ADDRESS VARCHAR2(2000),
    TIMESPAN VARCHAR2(2000),
    CONSTRAINT SWITCH_STATION_PK PRIMARY KEY (STATION_ID)
);

CREATE TABLE VEHICLE (
    VEHICLE_ID NUMBER(19, 0) NOT NULL,
    PURCHASE_DATE TIMESTAMP(7) NOT NULL,
    BATTERY_ID NUMBER(19, 0) NOT NULL,
    PLATE_NUMBER VARCHAR2(2000),
    MILEAGE NUMBER NOT NULL,
    TEMPERATURE NUMBER NOT NULL,
    WARRANTY TIMESTAMP(7) NOT NULL,
    OWNER_ID NUMBER(19, 0) NOT NULL,
    VEHICLE_MODEL_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT VEHICLE_PK PRIMARY KEY (VEHICLE_ID),
    CONSTRAINT VEHICLE_FK1 FOREIGN KEY (BATTERY_ID) REFERENCES BATTERY(BATTERY_ID),
    CONSTRAINT VEHICLE_FK2 FOREIGN KEY (OWNER_ID) REFERENCES VEHICLE_OWNER(OWNER_ID),
    CONSTRAINT VEHICLE_FK3 FOREIGN KEY (VEHICLE_MODEL_ID) REFERENCES VEHICLE_PARAM(VEHICLE_MODEL)
);

CREATE TABLE VEHICLE_OWNER (
    OWNER_ID NUMBER(19, 0) NOT NULL,
    ACCOUNT_SERIAL VARCHAR2(2000),
    USERNAME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    PASSWORD VARCHAR2(50) NOT NULL,
    PROFILE_PHOTO BLOB,
    CREATE_TIME TIMESTAMP(7) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(3),
    BIRTHDAY TIMESTAMP(7),
    CONSTRAINT VEHICLE_OWNER_PK PRIMARY KEY (OWNER_ID)
);

CREATE TABLE VEHICLE_PARAM (
    VEHICLE_MODEL NUMBER(19, 0) NOT NULL,
    ModelNAME VARCHAR2(2000) NOT NULL,
    TRANSMISSION VARCHAR2(50) NOT NULL,
    SERVICE_TERM TIMESTAMP(7) NOT NULL,
    MANUFACTURER VARCHAR2(50) NOT NULL,
    MAX_SPEED NUMBER NOT NULL,
    SINP BLOB,
    CONSTRAINT VEHICLE_PARAM_PK PRIMARY KEY (VEHICLE_MODEL)
);

CREATE TABLE __EFMigrationsHistory (
    MigrationId VARCHAR2(150) NOT NULL,
    ProductVersion VARCHAR2(32) NOT NULL,
    CONSTRAINT EFMigrationsHistory_PK PRIMARY KEY (MigrationId)
);

-- 添加外键约束
ALTER TABLE SWITCH_LOG ADD CONSTRAINT SWITCH_LOG_FK4 FOREIGN KEY (SWITCH_REQUEST_ID) REFERENCES SWITCH_REQUEST(SWITCH_REQUEST_ID);
ALTER TABLE KPI ADD CONSTRAINT KPI_FK2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
ALTER TABLE VEHICLE_OWNER ADD CONSTRAINT VEHICLE_OWNER_FK1 FOREIGN KEY (OWNER_ID) REFERENCES VEHICLE(OWNER_ID);
ALTER TABLE VEHICLE_PARAM ADD CONSTRAINT VEHICLE_PARAM_FK1 FOREIGN KEY (VEHICLE_MODEL) REFERENCES VEHICLE(VEHICLE_MODEL_ID);
ALTER TABLE SWITCH_REQUEST ADD CONSTRAINT SWITCH_REQUEST_FK4 FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID);
ALTER TABLE SWITCH_REQUEST ADD CONSTRAINT SWITCH_REQUEST_FK5 FOREIGN KEY (BATTERY_TYPE_ID) REFERENCES BATTERY_TYPE(BATTERY_TYPE_ID);
ALTER TABLE BATTERY_TYPE ADD CONSTRAINT BATTERY_TYPE_FK2 FOREIGN KEY (BATTERY_TYPE_ID) REFERENCES BATTERY(BATTERY_TYPE_ID);
ALTER TABLE SWITCH_STATION ADD CONSTRAINT SWITCH_STATION_FK1 FOREIGN KEY (STATION_ID) REFERENCES BATTERY(STATION_ID);
ALTER TABLE BATTERY ADD CONSTRAINT BATTERY_FK2 FOREIGN KEY (STATION_ID) REFERENCES SWITCH_STATION(STATION_ID);
ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_FK4 FOREIGN KEY (BATTERY_ID) REFERENCES BATTERY(BATTERY_ID);
ALTER TABLE OWNERPOS ADD CONSTRAINT OWNERPOS_FK1 FOREIGN KEY (OWNER_ID) REFERENCES VEHICLE_OWNER(OWNER_ID);
ALTER TABLE MAINTENANCE_ITEM ADD CONSTRAINT MAINTENANCE_ITEM_FK2 FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID);
ALTER TABLE SWITCH_LOG ADD CONSTRAINT SWITCH_LOG_FK1 FOREIGN KEY (BATTERY_ON_ID) REFERENCES BATTERY(BATTERY_ID);
ALTER TABLE SWITCH_LOG ADD CONSTRAINT SWITCH_LOG_FK2 FOREIGN KEY (BATTERY_OFF_IF) REFERENCES BATTERY(BATTERY_ID);
ALTER TABLE SWITCH_STATION ADD CONSTRAINT SWITCH_STATION_FK2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY (STATION_ID) REFERENCES SWITCH_STATION(STATION_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_FK2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES SWITCH_REQUEST(EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_MAINTENANCEITEM ADD CONSTRAINT EMPLOYEE_MAINTENANCEITEM_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_MAINTENANCEITEM ADD CONSTRAINT EMPLOYEE_MAINTENANCEITEM_FK2 FOREIGN KEY (MAINTENANCE_ID) REFERENCES MAINTENANCE_ITEM(MAINTENANCE_ITEM_ID);
